# Generated by Django 3.0.2 on 2020-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altroochat', '0002_auto_20200123_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='chat_attachment'),
        ),
    ]
