# Generated by Django 3.0.2 on 2020-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altroochat', '0003_auto_20200123_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
